/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import {Route as rootRoute} from './routes/__root'
import {Route as GotoImport} from './routes/goto'
import {Route as IndexImport} from './routes/index'

// Create/Update Routes

const GotoRoute = GotoImport.update({
  id: '/goto',
  path: '/goto',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/goto': {
      id: '/goto'
      path: '/goto'
      fullPath: '/goto'
      preLoaderRoute: typeof GotoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goto': typeof GotoRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goto': typeof GotoRoute
}

export interface FileRoutesById {
  '__root__': typeof rootRoute
  '/': typeof IndexRoute
  '/goto': typeof GotoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/goto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/goto'
  id: '__root__' | '/' | '/goto'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GotoRoute: typeof GotoRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GotoRoute: GotoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/goto"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/goto": {
      "filePath": "goto.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
