/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type {createStart} from '@tanstack/react-start'
import type {getRouter} from './router.tsx'
import {Route as rootRouteImport} from './routes/__root'
import {Route as ApiRevalidateTagsRouteImport} from './routes/api/revalidate-tags'
import {Route as IndexRouteImport} from './routes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateTagsRoute = ApiRevalidateTagsRouteImport.update({
  id: '/api/revalidate-tags',
  path: '/api/revalidate-tags',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/revalidate-tags': typeof ApiRevalidateTagsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/revalidate-tags': typeof ApiRevalidateTagsRoute
}
export interface FileRoutesById {
  '__root__': typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/revalidate-tags': typeof ApiRevalidateTagsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/revalidate-tags'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/revalidate-tags'
  id: '__root__' | '/' | '/api/revalidate-tags'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRevalidateTagsRoute: typeof ApiRevalidateTagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate-tags': {
      id: '/api/revalidate-tags'
      path: '/api/revalidate-tags'
      fullPath: '/api/revalidate-tags'
      preLoaderRoute: typeof ApiRevalidateTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRevalidateTagsRoute: ApiRevalidateTagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
