name: Auto format

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  if-needed:
    uses: sanity-io/.github/.github/workflows/format.yml@main
    secrets: inherit
